Repository chartjs/awesome, pull requests merged in 2022-12, with the labels that each got.

#54 Update v4 suppor for treemap/autocolors/gradient
  README.md
Labels: update

#58 chore: Remove clearly unmaintained libraries
  README.md
Labels: removal

#56 Add link for Blazor
  README.md
Labels: addition
